### PR TITLE
hashem's dummy commit CAPS ayo

### PR DESCRIPTION
**Pull request by alhindi01**
# Description

- modified text to caps

### CODE REVIEW

**Comment by alhindi01** [comment]
@Tayrika 
please review^^

**Comment by Tayrika** [comment]
https://media4.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif?cid=47028fa87k40eht04wowr73fdbt38jla6svo7yzd9kembf70&ep=v1_gifs&rid=giphy.gif&ct=g

**Comment by Tayrika** [comment]
image

**Comment by Tayrika** [comment]
https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXlrcjU2bm0yaXMzYWp6OXl1czI5N3hsNGR3YjF5bjV4ZzVmbnJqdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gLu90OMjz4j3hAkJk2/giphy.gif

**Comment by Tayrika** [comment]
Alt Text

**Pull request merged**
